// <auto-generated />
using Hippo.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hippo.Migrations.Migrations
{
    [DbContext(typeof(HippoDbContext))]
    [Migration("20260928195655_Files")]
    partial class Files
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Hippo.Migrations.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Frontmatter")
                        .HasColumnType("TEXT")
                        .HasColumnName("frontmatter");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<long>("Mtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mtime");

                    b.Property<string>("ParseError")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_error");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_files_path");

                    b.ToTable("files", null, t =>
                        {
                            t.HasCheckConstraint("ck_files_kind", "kind IN ('markdown', 'plain')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
