// <auto-generated />
using Hippo.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hippo.Migrations.Migrations
{
    [DbContext(typeof(HippoDbContext))]
    [Migration("20260929184740_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Hippo.Migrations.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Frontmatter")
                        .HasColumnType("TEXT")
                        .HasColumnName("frontmatter");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<long>("HashedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hashed_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<long>("Mtime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mtime");

                    b.Property<string>("ParseError")
                        .HasColumnType("TEXT")
                        .HasColumnName("parse_error");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ix_files_path");

                    b.ToTable("files", null, t =>
                        {
                            t.HasCheckConstraint("ck_files_kind", "kind IN ('markdown', 'other')");
                        });
                });

            modelBuilder.Entity("Hippo.Migrations.LinkEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<long>("Line")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_id");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_links_source_id");

                    b.HasIndex("Target")
                        .HasDatabaseName("ix_links_target");

                    b.ToTable("links", null, t =>
                        {
                            t.HasCheckConstraint("ck_links_kind", "kind IN ('body', 'frontmatter')");

                            t.HasCheckConstraint("ck_links_target", "type = 'path' OR target IS NULL");

                            t.HasCheckConstraint("ck_links_type", "type IN ('path', 'url', 'anchor')");
                        });
                });

            modelBuilder.Entity("Hippo.Migrations.MetaEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("Hippo.Migrations.LinkEntity", b =>
                {
                    b.HasOne("Hippo.Migrations.FileEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
