#!/usr/bin/env python3
"""Writes src/Hippo/Workspaces/Nfd.Tables.cs, the Unicode data Nfd reads, from the Unicode database of the Python that
runs it. hippo runs with invariant globalization, where .NET's own normalization does nothing, so it carries these.
Run it again to move to a newer Unicode version: canonical decompositions never change once assigned, so a newer
version only adds characters."""

import pathlib
import unicodedata

HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3
SURROGATE_FIRST, SURROGATE_LAST = 0xD800, 0xDFFF


def code_points():
    for cp in range(0x110000):
        if not SURROGATE_FIRST <= cp <= SURROGATE_LAST:
            yield cp


def rows(values, per_line):
    for start in range(0, len(values), per_line):
        yield "        " + ", ".join(values[start:start + per_line]) + ","


def span(name, element, values, per_line, doc):
    return [f"    /// <summary>{doc}</summary>",
            f"    private static ReadOnlySpan<{element}> {name} =>",
            "    [",
            *rows(values, per_line),
            "    ];",
            ""]


def main():
    # Hangul syllables decompose by arithmetic, so they need no table.
    decomposed, starts, decompositions = [], [0], []
    for cp in code_points():
        if HANGUL_FIRST <= cp <= HANGUL_LAST:
            continue
        nfd = unicodedata.normalize("NFD", chr(cp))
        if nfd != chr(cp):
            decomposed.append(cp)
            decompositions.extend(ord(c) for c in nfd)
            starts.append(len(decompositions))

    first, last, classes = [], [], []
    for cp in code_points():
        ccc = unicodedata.combining(chr(cp))
        if ccc == 0:
            continue
        if last and last[-1] == cp - 1 and classes[-1] == ccc:
            last[-1] = cp
        else:
            first.append(cp)
            last.append(cp)
            classes.append(ccc)

    hex_ = lambda values: [f"0x{v:04X}" for v in values]
    lines = [
        "// <auto-generated>",
        f"// Written by scripts/nfd-tables.py from Unicode {unicodedata.unidata_version}. Do not edit.",
        "// </auto-generated>",
        "",
        "namespace Hippo.Workspaces;",
        "",
        "internal static partial class Nfd",
        "{",
        *span("Decomposed", "int", hex_(decomposed), 12,
              "Every code point with a canonical decomposition, Hangul syllables aside, in ascending order."),
        *span("DecompositionStarts", "ushort", [str(s) for s in starts], 16,
              "Where each <see cref=\"Decomposed\"/> code point's decomposition starts in <see cref=\"Decompositions\"/>, "
              "and one past the last."),
        *span("Decompositions", "int", hex_(decompositions), 12,
              "The full canonical decompositions, already in canonical order, one after another."),
        *span("CombiningFirst", "int", hex_(first), 12,
              "The first code point of each run with one nonzero canonical combining class, in ascending order."),
        *span("CombiningLast", "int", hex_(last), 12, "The last code point of each run."),
        *span("CombiningClasses", "byte", [str(c) for c in classes], 24, "The combining class of each run."),
    ]
    lines[-1:] = ["}"]
    path = pathlib.Path(__file__).resolve().parent.parent / "src/Hippo/Workspaces/Nfd.Tables.cs"
    path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {path}: {len(decomposed)} decompositions, {len(first)} combining runs, Unicode {unicodedata.unidata_version}.")


if __name__ == "__main__":
    main()
